# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        users_in_memory:
            memory:
                users:
                    ryan:
                        password: ryanpass
                        roles: 'ROLE_USER'
                    admin:
                        password: helloworld
                        roles: 'ROLE_ADMIN'
        in_memory:
            memory: ~

    firewalls:
    
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: users_in_memory

            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login: 
                default_target_path: listarMascotas
                login_path: login
                check_path: login
    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: '^/admin', roles: [ROLE_ADMIN] }
        - { path: '^/mascotas/*', roles: [ROLE_ADMIN] }


    encoders:
        Symfony\Component\Security\Core\User\User: plaintext